on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-packadge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - run: npm install @vscode/vsce --save-dev 
    # Run the packadge.json script
    - run: npm run build
    - uses: actions/upload-artifact@v4
      with:
        name: wpgtk-theme-*.vsix
        path: .