on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-packadge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Change package version number 
      run:  'sed -i "s%  \"version\": .*%  \"version\": \"${{ github.ref_name }}\",%g" ./package.json'
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
    - name: Install install vsce # Run the packadge.json script
      run: npm install @vscode/vsce --save-dev 
    - name: build package
      run: npm run build
    - name: upload file to release
      uses: Shopify/upload-to-release@v2.0.0
      with:
        name: wpgtk-theme-${{ github.ref_name }}.vsix
        path: ./wpgtk-theme-${{ github.ref_name }}.vsix
        repo-token: ${{ secrets.GITHUB_TOKEN }}